export default class DemoConstants{
  static readonly DEMO_APP_MMKV_ID = "DemoApp";
  static readonly LOGIN_PHONE_REGION_CODE = "LoginPhoneRegionCode";
  static readonly LOGIN_PHONE_NUMBER = "LoginPhoneNumber";
  static readonly LOGIN_USER_ID = "LoginUserID";
  static readonly LOGIN_USER_SIG = "LoginUserSig";
  static readonly LOGIN_TOKEN = "LoginToken";
  static readonly AUTO_LOGIN = "AutoLogin";
}
