export { C2CChatSettingView } from './pages/C2CChatSettingView';

export { GroupChatSettingView } from './pages/GroupChatSettingView';

export { GroupManagementView } from './pages/GroupManagementView';

export { GroupMemberListPage } from './pages/GroupMemberListPage';

export { GroupAnnouncementView } from './pages/GroupAnnouncementView';

export { GroupPermissionManager, GroupPermission } from './manager/GroupPermissionManager';

export {
  JoinGroupMethodDialog,
  InviteGroupMethodDialog,
  GroupNameEditDialog,
  ActionButtonConfig
} from './dialog/GroupSettingDialogs';
