export class Colors {
  // 黑色系
  static Black1: string = '#FF000000';
  static Black2: string = '#E6000000';
  static Black3: string = '#B8000000';
  static Black4: string = '#8C000000';
  static Black5: string = '#66000000';
  static Black6: string = '#40000000';
  static Black7: string = '#1F000000';
  static Black8: string = '#0F000000';
  // 白色系
  static White1: string = '#FFFFFFFF';
  static White2: string = '#EDFFFFFF';
  static White3: string = '#BFFFFFFF';
  static White4: string = '#8CFFFFFF';
  static White5: string = '#6BFFFFFF';
  static White6: string = '#4DFFFFFF';
  static White7: string = '#24FFFFFF';
  // 灰色系-浅
  static GrayLight1: string = '#FFF9FAFC';
  static GrayLight2: string = '#FFF0F2F7';
  static GrayLight3: string = '#FFE6E9F0';
  static GrayLight4: string = '#FFD1D4DE';
  static GrayLight5: string = '#FFC0C3CC';
  static GrayLight6: string = '#FFB3B6BE';
  static GrayLight7: string = '#FFA5A9B0';
  // 灰色系-深
  static GrayDark1: string = '#FF131417';
  static GrayDark2: string = '#FF1F2024';
  static GrayDark3: string = '#FF2B2C30';
  static GrayDark4: string = '#FF3A3C42';
  static GrayDark5: string = '#FF48494F';
  static GrayDark6: string = '#FF54565C';
  static GrayDark7: string = '#FF646A70';
  // 主题色-浅
  static ThemeLight1: string = '#FFEBF3FF';
  static ThemeLight2: string = '#FFCCE2FF';
  static ThemeLight3: string = '#FFADCFFF';
  static ThemeLight4: string = '#FF7AAFFF';
  static ThemeLight5: string = '#FF4588F5';
  static ThemeLight6: string = '#FF1C66E5';
  static ThemeLight7: string = '#FF0D49BF';
  static ThemeLight8: string = '#FF033099';
  static ThemeLight9: string = '#FF001F73';
  static ThemeLight10: string = '#FF00124D';
  // 主题色-深
  static ThemeDark1: string = '#FF1C2333';
  static ThemeDark2: string = '#FF243047';
  static ThemeDark3: string = '#FF2F4875';
  static ThemeDark4: string = '#FF305BA6';
  static ThemeDark5: string = '#FF2B6AD6';
  static ThemeDark6: string = '#FF4086FF';
  static ThemeDark7: string = '#FF5C9DFF';
  static ThemeDark8: string = '#FF78B0FF';
  static ThemeDark9: string = '#FF9CC7FF';
  static ThemeDark10: string = '#FFC2DEFF';
  // 绿色系-浅
  static GreenLight1: string = '#FFDCFAE9';
  static GreenLight2: string = '#FFB6F0D1';
  static GreenLight3: string = '#FF84E3B5';
  static GreenLight4: string = '#FF5AD69E';
  static GreenLight5: string = '#FF3CC98C';
  static GreenLight6: string = '#FF0ABF77';
  static GreenLight7: string = '#FF09A768';
  static GreenLight8: string = '#FF078F59';
  static GreenLight9: string = '#FF067049';
  static GreenLight10: string = '#FF044D37';
  // 绿色系-深
  static GreenDark1: string = '#FF1A2620';
  static GreenDark2: string = '#FF22352C';
  static GreenDark3: string = '#FF2F4F3F';
  static GreenDark4: string = '#FF377355';
  static GreenDark5: string = '#FF368F65';
  static GreenDark6: string = '#FF38A673';
  static GreenDark7: string = '#FF62B58B';
  static GreenDark8: string = '#FF8BC7A9';
  static GreenDark9: string = '#FFA9D4BD';
  static GreenDark10: string = '#FFC8E5D5';
  // 红色系-浅
  static RedLight1: string = '#FFFFE7E6';
  static RedLight2: string = '#FFFCC9C7';
  static RedLight3: string = '#FFFAAEAC';
  static RedLight4: string = '#FFF58989';
  static RedLight5: string = '#FFE86666';
  static RedLight6: string = '#FFE54545';
  static RedLight7: string = '#FFC93439';
  static RedLight8: string = '#FFAD2934';
  static RedLight9: string = '#FF8F222D';
  static RedLight10: string = '#FF6B1A27';
  // 红色系-深
  static RedDark1: string = '#FF2B1C1F';
  static RedDark2: string = '#FF422324';
  static RedDark3: string = '#FF613234';
  static RedDark4: string = '#FF8A4242';
  static RedDark5: string = '#FFC2544E';
  static RedDark6: string = '#FFE6594C';
  static RedDark7: string = '#FFE57A6E';
  static RedDark8: string = '#FFF3A599';
  static RedDark9: string = '#FFFACBC3';
  static RedDark10: string = '#FFFAE4DE';
  // 橙色系-浅
  static OrangeLight1: string = '#FFFFEEDB';
  static OrangeLight2: string = '#FFFFD6B2';
  static OrangeLight3: string = '#FFFFBE85';
  static OrangeLight4: string = '#FFFFA455';
  static OrangeLight5: string = '#FFFF8B2B';
  static OrangeLight6: string = '#FFFF7200';
  static OrangeLight7: string = '#FFE05D00';
  static OrangeLight8: string = '#FFBF4900';
  static OrangeLight9: string = '#FF8F370B';
  static OrangeLight10: string = '#FF662200';
  // 橙色系-深
  static OrangeDark1: string = '#FF211A19';
  static OrangeDark2: string = '#FF35231A';
  static OrangeDark3: string = '#FF462E1F';
  static OrangeDark4: string = '#FF653C21';
  static OrangeDark5: string = '#FF96562A';
  static OrangeDark6: string = '#FFE37F32';
  static OrangeDark7: string = '#FFE39552';
  static OrangeDark8: string = '#FFEEAD72';
  static OrangeDark9: string = '#FFF7CFA4';
  static OrangeDark10: string = '#FFF9E9D1';
  // 透明
  static Transparent: string = '#00FFFFFF';
  // 强调色-浅
  static AccentTurquoiseLight: string = '#FF00ABD6';
  static AccentPurpleLight: string = '#FF8157FF';
  static AccentMagentaLight: string = '#FFF5457F';
  static AccentOrangeLight: string = '#FFFF6A4C';
  // 强调色-深
  static AccentTurquoiseDark: string = '#FF008FB2';
  static AccentPurpleDark: string = '#FF693CF0';
  static AccentMagentaDark: string = '#FFC22F56';
  static AccentOrangeDark: string = '#FFF25B35';
}