tox:
  type: cloud
  target: flutter_for_web
  dist: build/web
  wework:
    ? chatid
  product:
    name: 即时通信IM
    id: CAT010102
  pipelineUrl: http://tencent.coding.woa.com/p/tx/ci/job/760344/build/current
  clashKey: 3dbf6e59e1959236a45177f67eba8809
