tox:
  type: cloud
  target: flutter
  dist: build/web
  wework:
    ? chatid
  product:
    name: 即时通信IM
    id: CAT010102
  pipelineUrl: http://tencent.coding.woa.com/p/tx/ci/job/830312/build/current
  clashKey: 3fdcabf62caa6808a1c95b0ab9c82aca
