# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TUIKitSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TUIKitSwiftDemo
  pod 'TXIMSDK_TUIKit_iOS', :path => "../../"
  pod 'TXIMSDK_iOS', :path => "../../"
end
