// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuSazGXGy3rO9_Icfme0VOWUyaSYoktHs',
    appId: '1:648596655528:web:385d76da5e44cc007fe19d',
    messagingSenderId: '648596655528',
    projectId: 'tencentcloud-im',
    authDomain: 'tencentcloud-im.firebaseapp.com',
    storageBucket: 'tencentcloud-im.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAchl9gN87F1MaCBL1jUr1gCLfhsX_YL7Y',
    appId: '1:648596655528:android:982a4a39035201997fe19d',
    messagingSenderId: '648596655528',
    projectId: 'tencentcloud-im',
    storageBucket: 'tencentcloud-im.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWukKi5yAYSP-35pzshNUTJGbzEBAe71o',
    appId: '1:648596655528:ios:5ce1cb99ee9f1a477fe19d',
    messagingSenderId: '648596655528',
    projectId: 'tencentcloud-im',
    storageBucket: 'tencentcloud-im.appspot.com',
    iosClientId: '648596655528-kafivq0ki0vj8pdq7n75399neq10ov53.apps.googleusercontent.com',
    iosBundleId: 'com.tencent.im.flutter.uikit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWukKi5yAYSP-35pzshNUTJGbzEBAe71o',
    appId: '1:648596655528:ios:a97698ee481cb1ff7fe19d',
    messagingSenderId: '648596655528',
    projectId: 'tencentcloud-im',
    storageBucket: 'tencentcloud-im.appspot.com',
    iosClientId: '648596655528-6mjipjaa7gegcsfr88fhsdvjcdp5gb86.apps.googleusercontent.com',
    iosBundleId: 'com.tencent.flutter.tuikit',
  );
}
