name: tencent_im_sdk_plugin_web
description: The web implementation of tencent_im_sdk_plugin.
version: 0.2.7

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "^2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  mime_type: ^1.0.0
  tencent_im_sdk_plugin_platform_interface: 
    path: ../tencent_im_sdk_plugin_platform_interface
  js: ^0.6.2
  path: ^1.8.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: tencent_im_sdk_plugin
    platforms:
      web:
        pluginClass: TencentImSDKPluginWeb
        fileName: tencent_im_sdk_plugin_web.dart