name: im_api_example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  expandable: ^5.0.1
  provider: ^5.0.0
  gradient_ui_widgets: ^1.0.2-nullsafety
  modal_bottom_sheet: ^2.0.0
  # tencent_im_sdk_plugin: ^3.8.8
  tencent_im_sdk_plugin: 
    path: /Users/xingchenhe/Documents/work/git.code.oa.com/im-flutter-plugin/tencent_im_sdk_plugin
  flutter_syntax_view: ^4.0.0
  loading_indicator: ^2.0.1
  crypto: ^3.0.1
  flutter_easyloading: ^3.0.0
  fluttertoast: ^8.0.6
  archive: ^3.1.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pretty_json: ^2.0.0 
  adaptive_action_sheet: ^2.0.0
  image_picker: ^0.8.4
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.1
  record: ^2.1.1
  geolocator: ^7.0.3
  # tpns_flutter_plugin: 
  #   path: /Users/xingchenhe/Documents/work/TPNS-Flutter-Plugin
  localstorage: ^4.0.0+1
  adaptive_dialog: ^0.10.0+5
  mime_type: ^1.0.0
  file_picker: ^4.2.1
  js_shims: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  fast_i18n: 5.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/im/initSDK.dart
    - lib/im/login.dart
    - lib/im/logout.dart
    - lib/im/addEventListener.dart
    - lib/im/getVersion.dart
    - lib/im/getUsersInfo.dart
    - lib/im/getLoginUser.dart
    - lib/im/getLoginStatus.dart
    - lib/im/createGroup.dart
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
