tox:
  type: cloud
  target: im/sdk/unity_plus
  dist: build
  wework:
    ? chatid
  product:
    name: 即时通信IM
    id: CAT010102
  pipelineUrl: http://tencent.coding.oa.com/p/tx/ci/job/388043/build/current
  clashKey: ee17d35612f3799a1e2ea48b38cbfa2b
