# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'TUIKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Pods for Example
  pod 'TUIChat', '7.2.4123'
  pod 'TIMCommon', '7.2.4123'
  pod 'TUIConversation', '7.2.4123'
  pod 'TUIContact', '7.2.4123'
  pod 'TUIGroup', '7.2.4123'
  pod 'TUISearch', '7.2.4123'
  pod 'TUIOfflinePush', '7.2.4123'
#  pod 'TUIPoll', '7.2.4123'
#  pod 'TUIGroupNote', '7.2.4123'
  pod 'TUICallKit'
  pod 'MJRefresh'
  pod 'Masonry'

end

#Pods config
#Fix Xcode14 Bundle target error
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|            
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['ENABLE_BITCODE'] = "NO"
        end
    end
end
