# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'TUIKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!

  # Pods for Example
  pod 'TUIChat', '6.5.2803'
  pod 'TUIConversation', '6.5.2803'
  pod 'TUIContact', '6.5.2803'
  pod 'TUIGroup', '6.5.2803'
  pod 'TUISearch', '6.5.2803'
  pod 'TUIOfflinePush', '6.5.2803'
  pod 'TUICalling'
  pod 'MJRefresh'
  pod 'TPNS-iOS'
end
