#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/bryceyxwang/Documents/flutter/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/bryceyxwang/Documents/project/im-flutter-plugin-fork/im-flutter-plugin/tencent_im_sdk_plugin/example"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/bryceyxwang/Documents/project/im-flutter-plugin-fork/im-flutter-plugin/tencent_im_sdk_plugin/example/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1.0.0"
export "EXCLUDED_ARCHS=arm64"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/bryceyxwang/Documents/project/im-flutter-plugin-fork/im-flutter-plugin/tencent_im_sdk_plugin/example/.dart_tool/package_config.json"
