export const COUNTRIES:Array<any> = [
  { zh_cn: '阿富汗', en: 'Afghanistan', phone: '93' },
  { zh_cn: '阿尔巴尼亚', en: 'Albania', phone: '355' },
  { zh_cn: '阿尔及利亚', en: 'Algeria', phone: '213' },
  { zh_cn: '美属萨摩亚', en: 'American Samoa', phone: '684' },
  { zh_cn: '安道尔', en: 'Andorra', phone: '376' },
  { zh_cn: '安哥拉', en: 'Angola', phone: '244' },
  { zh_cn: '安圭拉', en: 'Anguilla', phone: '1264' },
  { zh_cn: '南极洲', en: 'Antarctica', phone: '672' },
  { zh_cn: '安提瓜和巴布达', en: 'Antigua and Barbuda', phone: '1268' },
  { zh_cn: '阿根廷', en: 'Argentina', phone: '54' },
  { zh_cn: '亚美尼亚', en: 'Armenia', phone: '374' },
  { zh_cn: '阿鲁巴', en: 'Aruba', phone: '297' },
  { zh_cn: '澳大利亚', en: 'Australia', phone: '61' },
  { zh_cn: '奥地利', en: 'Austria', phone: '43' },
  { zh_cn: '阿塞拜疆', en: 'Azerbaijan', phone: '994' },
  { zh_cn: '巴林', en: 'Bahrain', phone: '973' },
  { zh_cn: '孟加拉国', en: 'Bangladesh', phone: '880' },
  { zh_cn: '巴巴多斯', en: 'Barbados', phone: '1246' },
  { zh_cn: '白俄罗斯', en: 'Belarus', phone: '375' },
  { zh_cn: '比利时', en: 'Belgium', phone: '32' },
  { zh_cn: '伯利兹', en: 'Belize', phone: '501' },
  { zh_cn: '贝宁', en: 'Benin', phone: '229' },
  { zh_cn: '百慕大', en: 'Bermuda', phone: '1441' },
  { zh_cn: '不丹', en: 'Bhutan', phone: '975' },
  { zh_cn: '玻利维亚', en: 'Bolivia', phone: '591' },
  { zh_cn: '波黑', en: 'Bosnia and Herzegovina', phone: '387' },
  { zh_cn: '博茨瓦纳', en: 'Botswana', phone: '267' },
  { zh_cn: '巴西', en: 'Brazil', phone: '55' },
  { zh_cn: '英属维尔京群岛', en: 'British Virgin Islands', phone: '1284' },
  { zh_cn: '文莱', en: 'Brunei Darussalam', phone: '673' },
  { zh_cn: '保加利亚', en: 'Bulgaria', phone: '359' },
  { zh_cn: '布基纳法索', en: 'Burkina Faso', phone: '226' },
  { zh_cn: '缅甸', en: 'Burma', phone: '95' },
  { zh_cn: '布隆迪', en: 'Burundi', phone: '257' },
  { zh_cn: '柬埔寨', en: 'Cambodia', phone: '855' },
  { zh_cn: '喀麦隆', en: 'Cameroon', phone: '237' },
  { zh_cn: '加拿大', en: 'Canada', phone: '1' },
  { zh_cn: '佛得角', en: 'Cape Verde', phone: '238' },
  { zh_cn: '开曼群岛', en: 'Cayman Islands', phone: '1345' },
  { zh_cn: '中非', en: 'Central African Republic', phone: '236' },
  { zh_cn: '乍得', en: 'Chad', phone: '235' },
  { zh_cn: '智利', en: 'Chile', phone: '56' },
  { zh_cn: '中国', en: 'China', phone: '86' },
  { zh_cn: '圣诞岛', en: 'Christmas Island', phone: '61' },
  { zh_cn: '科科斯（基林）群岛', en: 'Cocos (Keeling) Islands', phone: '61' },
  { zh_cn: '哥伦比亚', en: 'Colombia', phone: '57' },
  { zh_cn: '科摩罗', en: 'Comoros', phone: '269' },
  { zh_cn: '刚果（金）', en: 'Democratic Republic of the Congo', phone: '243' },
  { zh_cn: '刚果（布）', en: 'Republic of the Congo', phone: '242' },
  { zh_cn: '库克群岛', en: 'Cook Islands', phone: '682' },
  { zh_cn: '哥斯达黎加', en: 'Costa Rica', phone: '506' },
  { zh_cn: '科特迪瓦', en: 'Cote d\'Ivoire', phone: '225' },
  { zh_cn: '克罗地亚', en: 'Croatia', phone: '385' },
  // { zh_cn: '古巴', en: 'Cuba', phone: '53' },
  { zh_cn: '塞浦路斯', en: 'Cyprus', phone: '357' },
  { zh_cn: '捷克', en: 'Czech Republic', phone: '420' },
  { zh_cn: '丹麦', en: 'Denmark', phone: '45' },
  { zh_cn: '吉布提', en: 'Djibouti', phone: '253' },
  { zh_cn: '多米尼克', en: 'Dominica', phone: '1767' },
  { zh_cn: '多米尼加', en: 'Dominican Republic', phone: '1809' },
  { zh_cn: '厄瓜多尔', en: 'Ecuador', phone: '593' },
  { zh_cn: '埃及', en: 'Egypt', phone: '20' },
  { zh_cn: '萨尔瓦多', en: 'El Salvador', phone: '503' },
  { zh_cn: '赤道几内亚', en: 'Equatorial Guinea', phone: '240' },
  { zh_cn: '厄立特里亚', en: 'Eritrea', phone: '291' },
  { zh_cn: '爱沙尼亚', en: 'Estonia', phone: '372' },
  { zh_cn: '埃塞俄比亚', en: 'Ethiopia', phone: '251' },
  { zh_cn: '福克兰群岛（马尔维纳斯）', en: 'Falkland Islands (Islas Malvinas)', phone: '500' },
  { zh_cn: '法罗群岛', en: 'Faroe Islands', phone: '298' },
  { zh_cn: '斐济', en: 'Fiji', phone: '679' },
  { zh_cn: '芬兰', en: 'Finland', phone: '358' },
  { zh_cn: '法国', en: 'France', phone: '33' },
  { zh_cn: '法属圭亚那', en: 'French Guiana', phone: '594' },
  { zh_cn: '法属波利尼西亚', en: 'French Polynesia', phone: '689' },
  { zh_cn: '加蓬', en: 'Gabon', phone: '241' },
  { zh_cn: '格鲁吉亚', en: 'Georgia', phone: '995' },
  { zh_cn: '德国', en: 'Germany', phone: '49' },
  { zh_cn: '加纳', en: 'Ghana', phone: '233' },
  { zh_cn: '直布罗陀', en: 'Gibraltar', phone: '350' },
  { zh_cn: '希腊', en: 'Greece', phone: '30' },
  { zh_cn: '格陵兰', en: 'Greenland', phone: '299' },
  { zh_cn: '格林纳达', en: 'Grenada', phone: '1473' },
  { zh_cn: '瓜德罗普', en: 'Guadeloupe', phone: '590' },
  { zh_cn: '关岛', en: 'Guam', phone: '1671' },
  { zh_cn: '危地马拉', en: 'Guatemala', phone: '502' },
  { zh_cn: '根西岛', en: 'Guernsey', phone: '1481' },
  { zh_cn: '几内亚', en: 'Guinea', phone: '224' },
  { zh_cn: '几内亚比绍', en: 'Guinea-Bissau', phone: '245' },
  { zh_cn: '圭亚那', en: 'Guyana', phone: '592' },
  { zh_cn: '海地', en: 'Haiti', phone: '509' },
  { zh_cn: '梵蒂冈', en: 'Holy See (Vatican City)', phone: '379' },
  { zh_cn: '洪都拉斯', en: 'Honduras', phone: '504' },
  { zh_cn: '中国香港', en: 'Hong Kong (SAR)', phone: '852' },
  { zh_cn: '匈牙利', en: 'Hungary', phone: '36' },
  { zh_cn: '冰岛', en: 'Iceland', phone: '354' },
  { zh_cn: '印度', en: 'India', phone: '91' },
  { zh_cn: '印度尼西亚', en: 'Indonesia', phone: '62' },
  //  { zh_cn: '伊朗', en: 'Iran', phone: '98' },
  { zh_cn: '伊拉克', en: 'Iraq', phone: '964' },
  { zh_cn: '爱尔兰', en: 'Ireland', phone: '353' },
  { zh_cn: '以色列', en: 'Israel', phone: '972' },
  { zh_cn: '意大利', en: 'Italy', phone: '39' },
  { zh_cn: '牙买加', en: 'Jamaica', phone: '1876' },
  { zh_cn: '日本', en: 'Japan', phone: '81' },
  { zh_cn: '约旦', en: 'Jordan', phone: '962' },
  { zh_cn: '哈萨克斯坦', en: 'Kazakhstan', phone: '73' },
  { zh_cn: '肯尼亚', en: 'Kenya', phone: '254' },
  { zh_cn: '基里巴斯', en: 'Kiribati', phone: '686' },
  // { zh_cn: '朝鲜', en: 'North Korea', phone: '850' },
  { zh_cn: '韩国', en: 'South Korea', phone: '82' },
  { zh_cn: '科威特', en: 'Kuwait', phone: '965' },
  { zh_cn: '吉尔吉斯斯坦', en: 'Kyrgyzstan', phone: '996' },
  { zh_cn: '老挝', en: 'Laos', phone: '856' },
  { zh_cn: '拉脱维亚', en: 'Latvia', phone: '371' },
  { zh_cn: '黎巴嫩', en: 'Lebanon', phone: '961' },
  { zh_cn: '莱索托', en: 'Lesotho', phone: '266' },
  { zh_cn: '利比里亚', en: 'Liberia', phone: '231' },
  { zh_cn: '利比亚', en: 'Libya', phone: '218' },
  { zh_cn: '列支敦士登', en: 'Liechtenstein', phone: '423' },
  { zh_cn: '立陶宛', en: 'Lithuania', phone: '370' },
  { zh_cn: '卢森堡', en: 'Luxembourg', phone: '352' },
  { zh_cn: '中国澳门', en: 'Macao', phone: '853' },
  { zh_cn: '前南马其顿', en: 'The Former Yugoslav Republic of Macedonia', phone: '389' },
  { zh_cn: '马达加斯加', en: 'Madagascar', phone: '261' },
  { zh_cn: '马拉维', en: 'Malawi', phone: '265' },
  { zh_cn: '马来西亚', en: 'Malaysia', phone: '60' },
  { zh_cn: '马尔代夫', en: 'Maldives', phone: '960' },
  { zh_cn: '马里', en: 'Mali', phone: '223' },
  { zh_cn: '马耳他', en: 'Malta', phone: '356' },
  { zh_cn: '马绍尔群岛', en: 'Marshall Islands', phone: '692' },
  { zh_cn: '马提尼克', en: 'Martinique', phone: '596' },
  { zh_cn: '毛里塔尼亚', en: 'Mauritania', phone: '222' },
  { zh_cn: '毛里求斯', en: 'Mauritius', phone: '230' },
  { zh_cn: '马约特', en: 'Mayotte', phone: '269' },
  { zh_cn: '墨西哥', en: 'Mexico', phone: '52' },
  { zh_cn: '密克罗尼西亚', en: 'Federated States of Micronesia', phone: '691' },
  { zh_cn: '摩尔多瓦', en: 'Moldova', phone: '373' },
  { zh_cn: '摩纳哥', en: 'Monaco', phone: '377' },
  { zh_cn: '蒙古', en: 'Mongolia', phone: '976' },
  { zh_cn: '蒙特塞拉特', en: 'Montserrat', phone: '1664' },
  { zh_cn: '摩洛哥', en: 'Morocco', phone: '212' },
  { zh_cn: '莫桑比克', en: 'Mozambique', phone: '258' },
  { zh_cn: '纳米尼亚', en: 'Namibia', phone: '264' },
  { zh_cn: '瑙鲁', en: 'Nauru', phone: '674' },
  { zh_cn: '尼泊尔', en: 'Nepal', phone: '977' },
  { zh_cn: '荷兰', en: 'Netherlands', phone: '31' },
  { zh_cn: '荷属安的列斯', en: 'Netherlands Antilles', phone: '599' },
  { zh_cn: '新喀里多尼亚', en: 'New Caledonia', phone: '687' },
  { zh_cn: '新西兰', en: 'New Zealand', phone: '64' },
  { zh_cn: '尼加拉瓜', en: 'Nicaragua', phone: '505' },
  { zh_cn: '尼日尔', en: 'Niger', phone: '227' },
  { zh_cn: '尼日利亚', en: 'Nigeria', phone: '234' },
  { zh_cn: '纽埃', en: 'Niue', phone: '683' },
  { zh_cn: '诺福克岛', en: 'Norfolk Island', phone: '6723' },
  { zh_cn: '北马里亚纳', en: 'Northern Mariana Islands', phone: '1' },
  { zh_cn: '挪威', en: 'Norway', phone: '47' },
  { zh_cn: '阿曼', en: 'Oman', phone: '968' },
  { zh_cn: '巴基斯坦', en: 'Pakistan', phone: '92' },
  { zh_cn: '帕劳', en: 'Palau', phone: '680' },
  { zh_cn: '巴拿马', en: 'Panama', phone: '507' },
  { zh_cn: '巴布亚新几内亚', en: 'Papua New Guinea', phone: '675' },
  { zh_cn: '巴拉圭', en: 'Paraguay', phone: '595' },
  { zh_cn: '秘鲁', en: 'Peru', phone: '51' },
  { zh_cn: '菲律宾', en: 'Philippines', phone: '63' },
  { zh_cn: '波兰', en: 'Poland', phone: '48' },
  { zh_cn: '葡萄牙', en: 'Portugal', phone: '351' },
  { zh_cn: '波多黎各', en: 'Puerto Rico', phone: '1809' },
  { zh_cn: '卡塔尔', en: 'Qatar', phone: '974' },
  { zh_cn: '留尼汪', en: 'Reunion', phone: '262' },
  { zh_cn: '罗马尼亚', en: 'Romania', phone: '40' },
  { zh_cn: '俄罗斯', en: 'Russia', phone: '7' },
  { zh_cn: '卢旺达', en: 'Rwanda', phone: '250' },
  { zh_cn: '圣赫勒拿', en: 'Saint Helena', phone: '290' },
  { zh_cn: '圣基茨和尼维斯', en: 'Saint Kitts and Nevis', phone: '1869' },
  { zh_cn: '圣卢西亚', en: 'Saint Lucia', phone: '1758' },
  { zh_cn: '圣皮埃尔和密克隆', en: 'Saint Pierre and Miquelon', phone: '508' },
  { zh_cn: '圣文森特和格林纳丁斯', en: 'Saint Vincent and the Grenadines', phone: '1784' },
  { zh_cn: '萨摩亚', en: 'Samoa', phone: '685' },
  { zh_cn: '圣马力诺', en: 'San Marino', phone: '378' },
  { zh_cn: '圣多美和普林西比', en: 'Sao Tome and Principe', phone: '239' },
  { zh_cn: '沙特阿拉伯', en: 'Saudi Arabia', phone: '966' },
  { zh_cn: '塞内加尔', en: 'Senegal', phone: '221' },
  { zh_cn: '塞尔维亚和黑山', en: 'Serbia and Montenegro', phone: '381' },
  { zh_cn: '塞舌尔', en: 'Seychelles', phone: '248' },
  { zh_cn: '塞拉利', en: 'Sierra Leone', phone: '232' },
  { zh_cn: '新加坡', en: 'Singapore', phone: '65' },
  { zh_cn: '斯洛伐克', en: 'Slovakia', phone: '421' },
  { zh_cn: '斯洛文尼亚', en: 'Slovenia', phone: '386' },
  { zh_cn: '所罗门群岛', en: 'Solomon Islands', phone: '677' },
  { zh_cn: '索马里', en: 'Somalia', phone: '252' },
  { zh_cn: '南非', en: 'South Africa', phone: '27' },
  { zh_cn: '西班牙', en: 'Spain', phone: '34' },
  { zh_cn: '斯里兰卡', en: 'Sri Lanka', phone: '94' },
  { zh_cn: '苏丹', en: 'Sudan', phone: '249' },
  { zh_cn: '苏里南', en: 'Suriname', phone: '597' },
  { zh_cn: '斯瓦尔巴岛和扬马延岛', en: 'Svalbard', phone: '47' },
  { zh_cn: '斯威士兰', en: 'Swaziland', phone: '268' },
  { zh_cn: '瑞典', en: 'Sweden', phone: '46' },
  { zh_cn: '瑞士', en: 'Switzerland', phone: '41' },
  // { zh_cn: '叙利亚', en: 'Syria', phone: '963' },
  { zh_cn: '中国台湾', en: 'Taiwan', phone: '886' },
  { zh_cn: '塔吉克斯坦', en: 'Tajikistan', phone: '992' },
  { zh_cn: '坦桑尼亚', en: 'Tanzania', phone: '255' },
  { zh_cn: '泰国', en: 'Thailand', phone: '66' },
  { zh_cn: '巴哈马', en: 'The Bahamas', phone: '1242' },
  { zh_cn: '冈比亚', en: 'The Gambia', phone: '220' },
  { zh_cn: '多哥', en: 'Togo', phone: '228' },
  { zh_cn: '托克劳', en: 'Tokelau', phone: '690' },
  { zh_cn: '汤加', en: 'Tonga', phone: '676' },
  { zh_cn: '特立尼达和多巴哥', en: 'Trinidad and Tobago', phone: '1868' },
  { zh_cn: '突尼斯', en: 'Tunisia', phone: '216' },
  { zh_cn: '土耳其', en: 'Turkey', phone: '90' },
  { zh_cn: '土库曼斯坦', en: 'Turkmenistan', phone: '993' },
  { zh_cn: '特克斯和凯科斯群岛', en: 'Turks and Caicos Islands', phone: '1649' },
  { zh_cn: '图瓦卢', en: 'Tuvalu', phone: '688' },
  { zh_cn: '乌干达', en: 'Uganda', phone: '256' },
  { zh_cn: '乌克兰', en: 'Ukraine', phone: '380' },
  { zh_cn: '阿拉伯联合酋长国', en: 'United Arab Emirates', phone: '971' },
  { zh_cn: '英国', en: 'United Kingdom', phone: '44' },
  { zh_cn: '美国', en: 'United States', phone: '1' },
  { zh_cn: '乌拉圭', en: 'Uruguay', phone: '598' },
  { zh_cn: '乌兹别克斯坦', en: 'Uzbekistan', phone: '998' },
  { zh_cn: '瓦努阿图', en: 'Vanuatu', phone: '678' },
  { zh_cn: '委内瑞拉', en: 'Venezuela', phone: '58' },
  { zh_cn: '越南', en: 'Vietnam', phone: '84' },
  { zh_cn: '美属维尔京群岛', en: 'Virgin Islands', phone: '1340' },
  { zh_cn: '瓦利斯和富图纳', en: 'Wallis and Futuna', phone: '681' },
  { zh_cn: '也门', en: 'Yemen', phone: '967' },
  { zh_cn: '赞比亚', en: 'Zambia', phone: '260' },
  { zh_cn: '津巴布韦', en: 'Zimbabwe', phone: '263' }];
