version: v2.0
on:
  push: ["master"]
  mr:
    target-branches:
      - master
jobs:
  job_id_1:
    name: "Run unit test"
    runs-on: macos-latest
    steps:
    - name: "拉取GIT（命令行)"
      with:
        strategy: "FRESH_CHECKOUT"
      checkout: "self"
    - name: "单元测试-tencent_im_sdk_plugin"
      run: |
        export PATH=/Users/bkdevops/Library/apps/flutter/flutter_v2.5.2/bin:$PATH
        function test_plugin {
          cd tencent_im_sdk_plugin
          flutter pub get
          flutter test
        }

        function test_platform_interface {
          cd tencent_im_sdk_plugin_platform_interface
          flutter pub get
          flutter test
        }

        function test_plugin_web {
          cd ../tencent_im_sdk_plugin_web
          flutter pub get
          flutter test --platform chrome
        }
        
        test_platform_interface && test_plugin_web
