platform :ios, '8.0'
#source 'https://github.com/CocoaPods/Specs.git'

target 'TUICore' do
   # Comment the next line if you don't want to use dynamic frameworks
   # use_frameworks!

   # Pods for `YOUR_PROJECT_NAME`
   pod 'TXIMSDK_Plus_iOS', :path => "../../../../tuikit/ios/ImSDK/"
   pod 'ReactiveObjC'
   pod 'SDWebImage'
end

