# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'TUIKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!

  # Pods for Example
  pod 'TXIMSDK_TUIKit_iOS'
end
