# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TUIKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for Example
  pod 'MBProgressHUD'
  pod 'MMLayout'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'ReactiveObjC'
  pod 'MLeaksFinder'
  pod 'TXIMSDK_TUIKit_iOS'
end
