// Copyright (c) 2024 Tencent. All rights reserved.
// Author: eddardliu

#define VIDEO_EDIT_RESULT_CODE_NO_EDIT 1
#define VIDEO_EDIT_RESULT_CODE_GENERATE_SUCCESS   0
#define VIDEO_EDIT_RESULT_CODE_CANCEL   -1
#define VIDEO_EDIT_RESULT_CODE_GENERATE_FAIL -2

#define PHOTO_EDIT_RESULT_CODE_NO_EDIT 1
#define PHOTO_EDIT_RESULT_CODE_GENERATE_SUCCESS   0
#define PHOTO_EDIT_RESULT_CODE_CANCEL   -1
#define PHOTO_EDIT_RESULT_CODE_GENERATE_FAIL -2

#define SOURCE_TYPE_RECORD 1
#define SOURCE_TYPE_ALBUM 2
