platform :ios, '10.0'
#source 'https://github.com/CocoaPods/Specs.git'

target 'TIMCommon' do
   # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!

   # Pods for `YOUR_PROJECT_NAME`
   pod 'TUICore', :path => "../../TUICore/TUICore"
   pod 'TXIMSDK_Plus_iOS', :path => "../../../../tuikit/ios/ImSDK/"
   pod 'ReactiveObjC'
   pod 'SDWebImage'
end

